package HojaDeCuenta;

import HojaDeCuentaBE.MensualBE;
import HojaDeCuentaBL.cMensualBL;
import HojaDeCuentaBL.cMensualBLL;
import HojaDeCuentaC.Validar;
import ejecutar.Coneccion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;


public final class frmMensual extends javax.swing.JFrame {

    public boolean bNuevo = false;
    String[] Mes = {"MES", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"};
    int IdMes = 1;//1
    String annioActual;
    private int estableser;
    int habilitarCajastexto = 1;

    int insertar = 1;
    int actualizar = 2;
    int numeroDeEntradas = 0;
    List<MensualBE> lista = null;
    MensualBE mensualBE = null;
    int indiceEntradaActual = 0;
    
    public frmMensual() throws SQLException {
        super("HOJA DE CUENTA");
        /////////////////////////////////////////////////////
        JFrame.setDefaultLookAndFeelDecorated(true);
//        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
//        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteGlassSkin");
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessSkin");
        SubstanceLookAndFeel.setCurrentWatermark("org.jvnet.substance.watermark.SubstanceBinaryWatermark");
//        SubstanceLookAndFeel.setCurrentWatermark("org.jvnet.substance.watermark. SubstanceBubblesWatermark");
        setResizable(false);
        initComponents();
        /////////////////////////////////////////////////////
        this.setLocationRelativeTo(this);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/currency.png"));
        setIconImage(icon);
        setVisible(true);

//        cboBusqueda.SelectedIndex = 1;
//
//        VuelveACargarLista();

//        If grdBusqueda.Rows.Count = 0 Then
//            LimpiarCampos()
//            txtCodigo.Tag = ""
//            btnModificar.Enabled = False
//            btnEliminar.Enabled = False
//        Else
//            LlenarCamposDeFilaSeleccionada()
//        End If
        AsignarMes();
        Calendar c = new GregorianCalendar();
        jdcFecha.setDate(new Date());
        String dia = Integer.toString(c.get(Calendar.DATE));
        String mes = Integer.toString(c.get(Calendar.MONTH));
        annioActual = Integer.toString(c.get(Calendar.YEAR));
        jsnAnio.setValue(Integer.parseInt(annioActual));
//        estableser();
        lblId_Mes.setText("0");
        
        VuelveACargarLista();//por cuestiones de seguridad
        SetearCamposModoGrabado();
        if (numeroDeEntradas==0) {
            LimpiarCampos();
//            anteriorPosterior(false);
            lblMes.setText(Mes[0]);
        }else{
//            IdMes = obtenerFila02();
            IdMes = obtenerFilaEstablecida();
            AsignarMes();
//            anteriorPosterior(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSaldoAnteriorR1 = new javax.swing.JTextField();
        txtEntradaR1 = new javax.swing.JTextField();
        txtSalidaR1 = new javax.swing.JTextField();
        txtSaldoRestanteR1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnPosterior = new javax.swing.JButton();
        btnEstablecer = new javax.swing.JButton();
        lblMes = new javax.swing.JLabel();
        btnFiniquitar = new javax.swing.JButton();
        jsnAnio = new javax.swing.JSpinner();
        btnImprimir = new javax.swing.JButton();
        EGRESO = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoAnteriorR = new javax.swing.JTextField();
        txtEntradaR = new javax.swing.JTextField();
        txtSalidaR = new javax.swing.JTextField();
        txtSaldoRestanteR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSaldoAnteriorCC = new javax.swing.JTextField();
        txtEntradaCC = new javax.swing.JTextField();
        txtSalidaCC = new javax.swing.JTextField();
        txtSaldoRestanteCC = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSaldoAnteriorO = new javax.swing.JTextField();
        txtEntradaO = new javax.swing.JTextField();
        txtSalidaO = new javax.swing.JTextField();
        txtSaldoRestanteO = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtTotFondMes = new javax.swing.JTextField();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        lblId_Mes = new javax.swing.JLabel();
        jpCrud = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtTotalActuales = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtActual = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtTotalLargoPlazo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtLargoPlazo = new javax.swing.JTable();
        jpIngreso = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jpEgreso = new javax.swing.JPanel();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Recibido:"));

        jLabel6.setText("Saldo Anterior:");

        jLabel7.setText("ENTRADA:");

        jLabel8.setText("SALIDA:");

        jLabel9.setText("Saldo Restante:");

        txtSaldoAnteriorR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoAnteriorR1ActionPerformed(evt);
            }
        });

        txtEntradaR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaR1ActionPerformed(evt);
            }
        });

        txtSalidaR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaR1ActionPerformed(evt);
            }
        });

        txtSaldoRestanteR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoRestanteR1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(42, 42, 42)
                                .addComponent(txtSalidaR1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSaldoAnteriorR1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(txtEntradaR1)))
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSaldoRestanteR1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSaldoAnteriorR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEntradaR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSalidaR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSaldoRestanteR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPosterior.setText(">>");
        btnPosterior.setBorder(null);
        btnPosterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosteriorActionPerformed(evt);
            }
        });

        btnEstablecer.setText("E");
        btnEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstablecerActionPerformed(evt);
            }
        });

        btnFiniquitar.setText("Fin");
        btnFiniquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiniquitarActionPerformed(evt);
            }
        });

        jsnAnio.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2050, 1));
        jsnAnio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsnAnioStateChanged(evt);
            }
        });
        jsnAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsnAnioMouseClicked(evt);
            }
        });
        jsnAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsnAnioKeyPressed(evt);
            }
        });

        btnImprimir.setText("IM");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPosterior, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsnAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiniquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnterior)
                        .addComponent(jsnAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEstablecer)
                        .addComponent(btnFiniquitar)
                        .addComponent(btnImprimir))
                    .addComponent(lblMes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPosterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EGRESO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EGRESO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EGRESOMouseClicked(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setText("Saldo Anterior:");

        jLabel2.setText("ENTRADA:");

        jLabel3.setText("SALIDA:");

        jLabel4.setText("Saldo Restante:");

        txtSaldoAnteriorR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoAnteriorR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoAnteriorRActionPerformed(evt);
            }
        });
        txtSaldoAnteriorR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorRKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorRKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorRKeyReleased(evt);
            }
        });

        txtEntradaR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEntradaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaRActionPerformed(evt);
            }
        });
        txtEntradaR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaRKeyTyped(evt);
            }
        });

        txtSalidaR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSalidaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaRActionPerformed(evt);
            }
        });
        txtSalidaR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaRKeyTyped(evt);
            }
        });

        txtSaldoRestanteR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoRestanteR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoRestanteRActionPerformed(evt);
            }
        });
        txtSaldoRestanteR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoRestanteRKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalidaR, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtSaldoAnteriorR)
                            .addComponent(txtEntradaR))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSaldoRestanteR, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSaldoAnteriorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEntradaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalidaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSaldoRestanteR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Fecha:");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setText("Saldo Anterior:");

        jLabel11.setText("ENTRADA:");

        jLabel12.setText("SALIDA:");

        jLabel13.setText("Saldo Restante:");

        txtSaldoAnteriorCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoAnteriorCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoAnteriorCCActionPerformed(evt);
            }
        });
        txtSaldoAnteriorCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorCCKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorCCKeyReleased(evt);
            }
        });

        txtEntradaCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEntradaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaCCActionPerformed(evt);
            }
        });
        txtEntradaCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaCCKeyTyped(evt);
            }
        });

        txtSalidaCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSalidaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaCCActionPerformed(evt);
            }
        });
        txtSalidaCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaCCKeyTyped(evt);
            }
        });

        txtSaldoRestanteCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoRestanteCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoRestanteCCActionPerformed(evt);
            }
        });
        txtSaldoRestanteCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoRestanteCCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSaldoAnteriorCC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalidaCC)
                                    .addComponent(txtEntradaCC))))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSaldoRestanteCC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSaldoAnteriorCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEntradaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSalidaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSaldoRestanteCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setText("Saldo Anterior:");

        jLabel15.setText("ENTRADA:");

        jLabel16.setText("SALIDA:");

        jLabel17.setText("Saldo Restante:");

        txtSaldoAnteriorO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoAnteriorO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoAnteriorOActionPerformed(evt);
            }
        });
        txtSaldoAnteriorO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorOKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSaldoAnteriorOKeyReleased(evt);
            }
        });

        txtEntradaO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEntradaO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaOActionPerformed(evt);
            }
        });
        txtEntradaO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaOKeyTyped(evt);
            }
        });

        txtSalidaO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSalidaO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaOActionPerformed(evt);
            }
        });
        txtSalidaO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaOKeyTyped(evt);
            }
        });

        txtSaldoRestanteO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldoRestanteO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoRestanteOActionPerformed(evt);
            }
        });
        txtSaldoRestanteO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoRestanteOKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSaldoAnteriorO, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEntradaO)
                                    .addComponent(txtSalidaO))))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSaldoRestanteO, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSaldoAnteriorO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEntradaO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSalidaO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSaldoRestanteO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel18.setText("TOTAL DE FONDOS A FIN DE MES:");

        txtTotFondMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotFondMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotFondMesActionPerformed(evt);
            }
        });
        txtTotFondMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotFondMesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTotFondMes, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTotFondMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdcFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(65, 65, 65)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblId_Mes)))
                .addGap(13, 13, 13)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jScrollPane5.setViewportView(jScrollPane1);

        jpCrud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDeshacer.setText("Deshacer");
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCrudLayout = new javax.swing.GroupLayout(jpCrud);
        jpCrud.setLayout(jpCrudLayout);
        jpCrudLayout.setHorizontalGroup(
            jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrudLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(btnNuevo)
                .addGap(2, 2, 2)
                .addComponent(btnGrabar)
                .addGap(2, 2, 2)
                .addComponent(btnModificar)
                .addGap(2, 2, 2)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeshacer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCrudLayout.setVerticalGroup(
            jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGrabar)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar)
                    .addComponent(btnDeshacer)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCrud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        EGRESO.addTab("Conciliacion Hoja De Cuenta", jPanel12);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel19.setText("Total:");

        txtTotalActuales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotalActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActualesActionPerformed(evt);
            }
        });
        txtTotalActuales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalActualesKeyTyped(evt);
            }
        });

        jtActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title3"
            }
        ));
        jScrollPane3.setViewportView(jtActual);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalActuales, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTotalActuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel20.setText("Total:");

        txtTotalLargoPlazo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotalLargoPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalLargoPlazoActionPerformed(evt);
            }
        });
        txtTotalLargoPlazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalLargoPlazoKeyTyped(evt);
            }
        });

        jtLargoPlazo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtLargoPlazo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title3"
            }
        ));
        jScrollPane4.setViewportView(jtLargoPlazo);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalLargoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalLargoPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel11);

        EGRESO.addTab("Obligacion A Fin De Mes:", jScrollPane2);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIngresoLayout = new javax.swing.GroupLayout(jpIngreso);
        jpIngreso.setLayout(jpIngresoLayout);
        jpIngresoLayout.setHorizontalGroup(
            jpIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIngresoLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(201, 201, 201))
        );
        jpIngresoLayout.setVerticalGroup(
            jpIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        EGRESO.addTab("INGRESO", jpIngreso);

        javax.swing.GroupLayout jpEgresoLayout = new javax.swing.GroupLayout(jpEgreso);
        jpEgreso.setLayout(jpEgresoLayout);
        jpEgresoLayout.setHorizontalGroup(
            jpEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jpEgresoLayout.setVerticalGroup(
            jpEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        EGRESO.addTab("EGRESO", jpEgreso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EGRESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EGRESO))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoAnteriorR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoAnteriorR1ActionPerformed

    private void txtEntradaR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaR1ActionPerformed

    private void txtSalidaR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaR1ActionPerformed

    private void txtSaldoRestanteR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoRestanteR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoRestanteR1ActionPerformed

    private void txtTotalLargoPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalLargoPlazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalLargoPlazoActionPerformed

    private void txtTotalActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActualesActionPerformed

    private void txtTotFondMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotFondMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotFondMesActionPerformed

    private void txtSaldoRestanteOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoRestanteOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoRestanteOActionPerformed

    private void txtSalidaOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaOActionPerformed

    private void txtEntradaOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaOActionPerformed

    private void txtSaldoAnteriorOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoAnteriorOActionPerformed

    private void txtSaldoRestanteCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoRestanteCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoRestanteCCActionPerformed

    private void txtSalidaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaCCActionPerformed

    private void txtEntradaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaCCActionPerformed

    private void txtSaldoAnteriorCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoAnteriorCCActionPerformed

    private void txtSaldoRestanteRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoRestanteRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoRestanteRActionPerformed

    private void txtSalidaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaRActionPerformed

    private void txtEntradaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaRActionPerformed

    private void txtSaldoAnteriorRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoAnteriorRActionPerformed

    private void btnEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstablecerActionPerformed
        try {
//            JOptionPane.showMessageDialog(this, this.mensualBE.getEstableser());
                  
            SetearCamposModoGrabado();
            Coneccion c = new Coneccion();
            MensualBE mensualBE;
            cMensualBL mensualBL = new cMensualBL();
            int ires = 0;
            
            mensualBE = new MensualBE(5, Integer.parseInt(lblId_Mes.getText()), new Validar().fecha(jdcFecha), Float.parseFloat(txtSaldoAnteriorR.getText()), Float.parseFloat(txtEntradaR.getText()), Float.parseFloat(txtSalidaR.getText()), Float.parseFloat(txtSaldoRestanteR.getText()), Float.parseFloat(txtSaldoAnteriorCC.getText()), Float.parseFloat(txtEntradaCC.getText()), Float.parseFloat(txtSalidaCC.getText()), Float.parseFloat(txtSaldoRestanteCC.getText()), Float.parseFloat(txtSaldoAnteriorO.getText()), Float.parseFloat(txtEntradaO.getText()), Float.parseFloat(txtSalidaO.getText()), Float.parseFloat(txtSaldoRestanteO.getText()), Float.parseFloat(txtTotFondMes.getText()), 0//Float.parseFloat(txtTotalActuales.getText())
                , 0//Float.parseFloat(txtTotalLargoPlazo.getText())
                , 0, getEstableser(), "1");
            ires = mensualBL.Actualizar(c, mensualBE);
            if (ires < 0) {
                JOptionPane.showMessageDialog(this, "Error al Finiquitar");
            } else {
//                JOptionPane.showMessageDialog(this, "Exito al Finiquitar");
            }
//            JOptionPane.showMessageDialog(this, getEstableser());
            estableser();            
        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEstablecerActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        SetearCamposModoGrabado();
        try {
            if (Integer.parseInt(lblId_Mes.getText()) != 0) {
                Coneccion c = new Coneccion();
                MensualBE mensualBE = new MensualBE(2, 0, new Date(), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "0");
                cMensualBL mensualBL = new cMensualBL();
                if (mensualBL.Actualizar(c, mensualBE) < 0) {
                    JOptionPane.showMessageDialog(this, "No se elimino");
                }
            }
            VuelveACargarLista();
            if (lista == null) {
                LimpiarCampos();
                lblId_Mes.setText("0");
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
            } else {
                obtenerFila(0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
        bNuevo = false;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnPosteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosteriorActionPerformed
//        IdMes++;
//        AsignarMes();
//        if (this.lista!=null) {
//            obtenerFila(IdMes);
//        }
        indiceEntradaActual++;
        if (indiceEntradaActual >= numeroDeEntradas) {
            indiceEntradaActual = 0;
            IdMes = obtenerFila02();
            AsignarMes();
        }
    }//GEN-LAST:event_btnPosteriorActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
//        IdMes--;
//        AsignarMes();
//        if (this.lista!=null) {
//            obtenerFila(IdMes);
//        }
        //*****************************************************************
        indiceEntradaActual--;
        if (indiceEntradaActual < 0) {
            indiceEntradaActual = numeroDeEntradas - 1;
            IdMes = obtenerFila02();
            AsignarMes();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            habilitarCajastexto = 1;
            bNuevo = true;
            LimpiarCampos();
            jdcFecha.setFocusable(bNuevo);// es para focalizar
            Validar v = new Validar(insertar, new Date());
            
            if (v.getAntecesor()) {
                habilitarCajastexto = 0;//la existencia hace que se genere automaticamente
                if(v.getMensualBE().getGuardado()==1){
                    jdcFecha.setDate(v.sumarRestarDiasFecha(v.getMensualBE().getFecha(), 1));
                    cargarCamposNuevo(v.getMensualBE());
                    SetearCamposModoEdicion();
                }
                JOptionPane.showMessageDialog(rootPane, "Primero Finiquitar De la fecha "+v.getMensualBE().getFecha());
//                VuelveACargarLista();
                obtenerFila02();
            }else
            SetearCamposModoEdicion();

        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            if (Integer.parseInt(lblId_Mes.getText()) != 0) {
                habilitarCajastexto = 1;
                bNuevo = false;
                jdcFecha.setFocusCycleRoot(bNuevo);
                //capturamos valor de un jdate chooser y lo asignamos en una variable de tipo Date
//                Date date = new Date();//LUEGO ESOS PARAMATROS LO GUARDAMOS EN UNA VARIABLE
//                date = jdcFecha.getDate();
//                date.setYear(jdcFecha.getCalendar().get(Calendar.YEAR));

                Validar v = new Validar(actualizar, new Validar().fecha(jdcFecha));
                JOptionPane.showMessageDialog(rootPane, "VALIDO "+new Validar().fecha(jdcFecha));
                JOptionPane.showMessageDialog(rootPane, "Primero Finiquitar De la fecha "+v.getMensualBE().getFecha());
                if (v.getAntecesor()) {
                    habilitarCajastexto = 0;//la existencia hace que se genere automaticamente
                }
                SetearCamposModoEdicion();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
        SetearCamposModoGrabado();

//        If grdBusqueda.Rows.Count = 0 Then
//            LimpiarCampos()
//            txtCodigo.Tag = ""
//            btnModificar.Enabled = False
//            btnEliminar.Enabled = False
//        Else
//            LlenarCamposDeFilaSeleccionada()
//        End If
//
//        txtCodigo.Focus()
        bNuevo = false;
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try {
            SetearCamposModoGrabado();
            Coneccion c = new Coneccion();
            MensualBE mensualBE;
            cMensualBL mensualBL = new cMensualBL();
            int ires = 0;
            if (bNuevo) {
//                Date date = new Date();//LUEGO ESOS PARAMATROS LO GUARDAMOS EN UNA VARIABLE
//                date = jdcFecha.getDate();
//                date.setYear(jdcFecha.getCalendar().get(Calendar.YEAR));
                //************************************************************************
                mensualBE = new MensualBE(1, 0, new Validar().fecha(jdcFecha)//date
                        , Float.parseFloat(txtSaldoAnteriorR.getText()), Float.parseFloat(txtEntradaR.getText()), Float.parseFloat(txtSalidaR.getText()), Float.parseFloat(txtSaldoRestanteR.getText()), Float.parseFloat(txtSaldoAnteriorCC.getText()), Float.parseFloat(txtEntradaCC.getText()), Float.parseFloat(txtSalidaCC.getText()), Float.parseFloat(txtSaldoRestanteCC.getText()), Float.parseFloat(txtSaldoAnteriorO.getText()), Float.parseFloat(txtEntradaO.getText()), Float.parseFloat(txtSalidaO.getText()), Float.parseFloat(txtSaldoRestanteO.getText()), Float.parseFloat(txtTotFondMes.getText()), 0//Float.parseFloat(txtTotalActuales.getText())
                        , 0//Float.parseFloat(txtTotalLargoPlazo.getText())
                        , 0, this.estableser = 0, "1");
                ires = mensualBL.Insertar(c, mensualBE);
                if (ires < 0) {
                    JOptionPane.showMessageDialog(this, "Error al actualizar");
                    obtenerFila(Integer.parseInt(lblId_Mes.getText()));
                } else {
                    JOptionPane.showMessageDialog(this, "transaccion Exitosa");
                    VuelveACargarLista();
                    obtenerFila(ires);
                }
            } else {
                mensualBE = new MensualBE(3, Integer.parseInt(lblId_Mes.getText()), new Validar().fecha(jdcFecha), Float.parseFloat(txtSaldoAnteriorR.getText()), Float.parseFloat(txtEntradaR.getText()), Float.parseFloat(txtSalidaR.getText()), Float.parseFloat(txtSaldoRestanteR.getText()), Float.parseFloat(txtSaldoAnteriorCC.getText()), Float.parseFloat(txtEntradaCC.getText()), Float.parseFloat(txtSalidaCC.getText()), Float.parseFloat(txtSaldoRestanteCC.getText()), Float.parseFloat(txtSaldoAnteriorO.getText()), Float.parseFloat(txtEntradaO.getText()), Float.parseFloat(txtSalidaO.getText()), Float.parseFloat(txtSaldoRestanteO.getText()), Float.parseFloat(txtTotFondMes.getText()), 0//Float.parseFloat(txtTotalActuales.getText())
                        , 0//Float.parseFloat(txtTotalLargoPlazo.getText())
                        , 0, estableser = 0, "1");
                ires = mensualBL.Actualizar(c, mensualBE);
                if (ires < 0) {
                    JOptionPane.showMessageDialog(this, "Error al insertar");
                } else {
                    JOptionPane.showMessageDialog(this, "transaccion Exitosa");
                }
                VuelveACargarLista();
                obtenerFila(Integer.parseInt(lblId_Mes.getText()));
            }
            bNuevo = false;

        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnFiniquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiniquitarActionPerformed
        try {
            Coneccion c = new Coneccion();
            MensualBE mensualBE;
            cMensualBL mensualBL = new cMensualBL();
            int ires = 0;
            
            mensualBE = new MensualBE(4, Integer.parseInt(lblId_Mes.getText()), new Validar().fecha(jdcFecha), Float.parseFloat(txtSaldoAnteriorR.getText()), Float.parseFloat(txtEntradaR.getText()), Float.parseFloat(txtSalidaR.getText()), Float.parseFloat(txtSaldoRestanteR.getText()), Float.parseFloat(txtSaldoAnteriorCC.getText()), Float.parseFloat(txtEntradaCC.getText()), Float.parseFloat(txtSalidaCC.getText()), Float.parseFloat(txtSaldoRestanteCC.getText()), Float.parseFloat(txtSaldoAnteriorO.getText()), Float.parseFloat(txtEntradaO.getText()), Float.parseFloat(txtSalidaO.getText()), Float.parseFloat(txtSaldoRestanteO.getText()), Float.parseFloat(txtTotFondMes.getText()), 0//Float.parseFloat(txtTotalActuales.getText())
                , 0//Float.parseFloat(txtTotalLargoPlazo.getText())
                , 0, estableser = 0, "1");
            ires = mensualBL.Actualizar(c, mensualBE);
            if (ires < 0) {
                JOptionPane.showMessageDialog(this, "Error al Finiquitar");
            } else {
                JOptionPane.showMessageDialog(this, "Exito al Finiquitar");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFiniquitarActionPerformed

    private void jsnAnioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsnAnioKeyPressed
        JOptionPane.showMessageDialog(this, "Aqui el click");
    }//GEN-LAST:event_jsnAnioKeyPressed

    private void jsnAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsnAnioMouseClicked
        JOptionPane.showMessageDialog(this, "Aqui el click ojala");
    }//GEN-LAST:event_jsnAnioMouseClicked

    private void jsnAnioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsnAnioStateChanged
        try {
            VuelveACargarLista();
        } catch (SQLException ex) {
            Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jsnAnioStateChanged

    private void txtSaldoAnteriorRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorRKeyTyped
        keyTyped(evt, txtSaldoAnteriorR.getText());
//        try {
//            float a = Float.parseFloat(txtSaldoAnteriorR.getText());
//            float b = Float.parseFloat(txtSaldoAnteriorCC.getText());//float b = Float.parseFloat(txtEntradaR.getText());
//            float c = Float.parseFloat(txtSalidaR.getText());
//            a = a + b - c;
//            txtSaldoRestanteO.setText("" + a);
//        } catch (Exception e) {
//        }

    }//GEN-LAST:event_txtSaldoAnteriorRKeyTyped

    private void txtEntradaRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaRKeyTyped
        keyTyped(evt, txtEntradaR.getText());
    }//GEN-LAST:event_txtEntradaRKeyTyped

    private void txtSalidaRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaRKeyTyped
        keyTyped(evt, txtSalidaR.getText());
    }//GEN-LAST:event_txtSalidaRKeyTyped

    private void txtSaldoRestanteRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoRestanteRKeyTyped
        keyTyped(evt, txtSaldoRestanteR.getText());
    }//GEN-LAST:event_txtSaldoRestanteRKeyTyped

    private void txtSaldoAnteriorCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorCCKeyTyped
        keyTyped(evt, txtSaldoAnteriorCC.getText());
    }//GEN-LAST:event_txtSaldoAnteriorCCKeyTyped

    private void txtEntradaCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaCCKeyTyped
        keyTyped(evt, txtEntradaCC.getText());
    }//GEN-LAST:event_txtEntradaCCKeyTyped

    private void txtSalidaCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaCCKeyTyped
        keyTyped(evt, txtSalidaCC.getText());
    }//GEN-LAST:event_txtSalidaCCKeyTyped

    private void txtSaldoRestanteCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoRestanteCCKeyTyped
        keyTyped(evt, txtSaldoRestanteCC.getText());
    }//GEN-LAST:event_txtSaldoRestanteCCKeyTyped

    private void txtSaldoAnteriorOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorOKeyTyped
        keyTyped(evt, txtSaldoAnteriorO.getText());
    }//GEN-LAST:event_txtSaldoAnteriorOKeyTyped

    private void txtEntradaOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaOKeyTyped
        keyTyped(evt, txtEntradaO.getText());
    }//GEN-LAST:event_txtEntradaOKeyTyped

    private void txtSalidaOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaOKeyTyped
        keyTyped(evt, txtSalidaO.getText());
    }//GEN-LAST:event_txtSalidaOKeyTyped

    private void txtSaldoRestanteOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoRestanteOKeyTyped
        keyTyped(evt, txtSaldoRestanteO.getText());
    }//GEN-LAST:event_txtSaldoRestanteOKeyTyped

    private void txtTotFondMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotFondMesKeyTyped
        keyTyped(evt, txtTotFondMes.getText());
    }//GEN-LAST:event_txtTotFondMesKeyTyped

    private void txtTotalActualesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalActualesKeyTyped
        keyTyped(evt, txtTotalActuales.getText());
    }//GEN-LAST:event_txtTotalActualesKeyTyped

    private void txtTotalLargoPlazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalLargoPlazoKeyTyped
        keyTyped(evt, txtTotalLargoPlazo.getText());
    }//GEN-LAST:event_txtTotalLargoPlazoKeyTyped

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        MostrarResultadosConsulta consulta = new MostrarResultadosConsulta();
        consulta.show();
        consulta.setVisible(true);
        //SELECT id_mensual,fecha,estableser,flagactivo FROM MENSUAL
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void EGRESOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EGRESOMouseClicked
//        JOptionPane.showMessageDialog(this, "hola");
    }//GEN-LAST:event_EGRESOMouseClicked

    private void txtSaldoAnteriorRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorRKeyPressed
//        try {
////            float a = Float.parseFloat(txtSaldoAnteriorR.getText());
////            float b = Float.parseFloat(txtEntradaR.getText());//float b = Float.parseFloat(txtEntradaR.getText());
////            float c = Float.parseFloat(txtSalidaR.getText());
////            a = a + b - c;
//            txtSaldoRestanteR.setText(txtSaldoAnteriorR.getText());
////            JOptionPane.showMessageDialog(rootPane, "que ");
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_txtSaldoAnteriorRKeyPressed

    private void txtSaldoAnteriorRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorRKeyReleased
        try {
            float a = Float.parseFloat(txtSaldoAnteriorR.getText());
            float b = Float.parseFloat(txtEntradaR.getText());//float b = Float.parseFloat(txtEntradaR.getText());
            float c = Float.parseFloat(txtSalidaR.getText());
            a = a + b - c;
            txtSaldoRestanteR.setText(""+a);
            sumaTotal();
//            JOptionPane.showMessageDialog(rootPane, "que ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSaldoAnteriorRKeyReleased

    private void txtSaldoAnteriorCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorCCKeyReleased
        try {
            float a = Float.parseFloat(txtSaldoAnteriorCC.getText());
            float b = Float.parseFloat(txtEntradaCC.getText());//float b = Float.parseFloat(txtEntradaR.getText());
            float c = Float.parseFloat(txtSalidaCC.getText());
            a = a + b - c;
            txtSaldoRestanteCC.setText(""+a);
            sumaTotal();
//            JOptionPane.showMessageDialog(rootPane, "que ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSaldoAnteriorCCKeyReleased

    private void txtSaldoAnteriorOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAnteriorOKeyReleased
        try {
            float a = Float.parseFloat(txtSaldoAnteriorO.getText());
            float b = Float.parseFloat(txtEntradaO.getText());//float b = Float.parseFloat(txtEntradaR.getText());
            float c = Float.parseFloat(txtSalidaO.getText());
            a = a + b - c;
            txtSaldoRestanteO.setText(""+a);
            sumaTotal();
//            JOptionPane.showMessageDialog(rootPane, "que ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSaldoAnteriorOKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MostrarResultadosConsulta consulta = new MostrarResultadosConsulta();
        consulta.show();
        consulta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void keyTyped(java.awt.event.KeyEvent evt, String s) {
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)
                && (c != '.')) {
            evt.consume();
        }
        if (c == '.' && s.contains(".")) {
            evt.consume();
        }
    }

    private void SetearCamposModoGrabado() { //'no tocar'
        btnNuevo.setEnabled(true);
        btnGrabar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        DeshabilitarCampos();
    }

    private void SetearCamposModoEdicion() { //'no tocar'
        btnNuevo.setEnabled(false);
        btnGrabar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);

        HabilitarCampos();
    }
    private void SetearCamposModoEdicion02() { //'CUANDO SOLO EDITA LOS BOTONES'
        btnNuevo.setEnabled(false);
        btnGrabar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);

//        HabilitarCampos();
    }

    private void DeshabilitarCampos() {
        jdcFecha.setEnabled(false);
        txtSaldoAnteriorR.setEnabled(false);
        txtEntradaR.setEnabled(false);
        txtSalidaR.setEnabled(false);
        txtSaldoRestanteR.setEnabled(false);

        txtSaldoAnteriorCC.setEnabled(false);
        txtEntradaCC.setEnabled(false);
        txtSalidaCC.setEnabled(false);
        txtSaldoRestanteCC.setEnabled(false);

        txtSaldoAnteriorO.setEnabled(false);
        txtEntradaO.setEnabled(false);
        txtSalidaO.setEnabled(false);
        txtSaldoRestanteO.setEnabled(false);

        txtTotFondMes.setEnabled(false);
    }

    private void HabilitarCampos() {
        if (bNuevo) {
            jdcFecha.setEnabled((habilitarCajastexto == 1) ? true : false);
        }
        txtSaldoAnteriorR.setEnabled((habilitarCajastexto == 1) ? true : false);//***
//        txtEntradaR.setEnabled(true);
//        txtSalidaR.setEnabled(true);
//        txtSaldoRestanteR.setEnabled(true);
        txtEntradaR.setEnabled(false);
        txtSalidaR.setEnabled(false);
        txtSaldoRestanteR.setEnabled(false);

        txtSaldoAnteriorCC.setEnabled((habilitarCajastexto == 1) ? true : false);//***
//        txtEntradaCC.setEnabled(true);
//        txtSalidaCC.setEnabled(true);
//        txtSaldoRestanteCC.setEnabled(true);
        txtEntradaCC.setEnabled(false);
        txtSalidaCC.setEnabled(false);
        txtSaldoRestanteCC.setEnabled(false);

        txtSaldoAnteriorO.setEnabled((habilitarCajastexto == 1) ? true : false);//***
//        txtEntradaO.setEnabled(true);
//        txtSalidaO.setEnabled(true);
//        txtSaldoRestanteO.setEnabled(true);
        txtEntradaO.setEnabled(false);
        txtSalidaO.setEnabled(false);
        txtSaldoRestanteO.setEnabled(false);

        txtTotFondMes.setEnabled(false);
//        txtTotFondMes.setEnabled(true);
    }

    private void LimpiarCampos() {
//        //ENSAYO****************************
//        Validar validar = new Validar();
//        Date d = new Date();
//        //**********************************
//        jdcFecha.setDate(validar.sumarRestarDiasFecha( d, 1));
        lblId_Mes.setText("0");
        jdcFecha.setDate(new Date());
        txtSaldoAnteriorR.setText("0.00");
        txtEntradaR.setText("0.00");
        txtSalidaR.setText("0.00");
        txtSaldoRestanteR.setText("0.00");

        txtSaldoAnteriorCC.setText("0.00");
        txtEntradaCC.setText("0.00");
        txtSalidaCC.setText("0.00");
        txtSaldoRestanteCC.setText("0.00");

        txtSaldoAnteriorO.setText("0.00");
        txtEntradaO.setText("0.00");
        txtSalidaO.setText("0.00");
        txtSaldoRestanteO.setText("0.00");

        txtTotFondMes.setText("0.00");
    }

    public void AsignarMes() {
        if (IdMes == 13) {
            IdMes = 1;
        }
        if (IdMes == 0) {
            IdMes = 12;
        }
        lblMes.setText(Mes[IdMes]);
    }
    public void estableser() {
        //falta establecer a un registro unico
        if (getEstableser() == 0) {
//            this.estableser = 1;
            setEstableser(1);
            btnEstablecer.setText("D");
            btnFiniquitar.setEnabled(false);
            btnImprimir.setEnabled(false);
            anteriorPosterior(true);
//            btnPosterior.setEnabled(true);
//            btnAnterior.setEnabled(true);
//            jsnAnio.setEnabled(true);
            jpCrud.setVisible(true);
        } else {
//            this.estableser = 0;
            setEstableser(0);
            btnEstablecer.setText("E");
            btnFiniquitar.setEnabled(true);
            btnImprimir.setEnabled(true);
            anteriorPosterior(false);
//            btnPosterior.setEnabled(false);
//            btnAnterior.setEnabled(false);
//            jsnAnio.setEnabled(false);
            jpCrud.setVisible(false);
        }
    }
    public void anteriorPosterior(boolean b){
            btnPosterior.setEnabled(b);
            btnAnterior.setEnabled(b);
            jsnAnio.setEnabled(b);
    }
    public void VuelveACargarLista() throws SQLException {
        this.numeroDeEntradas = 0;
        this.lista = null;
        MensualBE mensualBE = new MensualBE(5, (int) jsnAnio.getValue(), new Validar().fecha(jdcFecha), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "1");
        cMensualBLL mensualBLL = new cMensualBLL();
        this.lista = mensualBLL.Leer(new Coneccion(), mensualBE);
        if (this.lista != null) {
            numeroDeEntradas = this.lista.size();
        }
    }

    public void obtenerFila(int Id_Mensual) {
        int cont = 1;
        if (numeroDeEntradas != 0) {
            for (MensualBE listaBE : this.lista) {
                if (Id_Mensual != 0 && Id_Mensual == listaBE.getId_Mensual()) {
                    cargarCampos(listaBE);
                } else {
                    if (cont == 1) {
                        cargarCampos(listaBE);
                        cont = 0;
                    }
                }
            }
        }
    }

    public int obtenerFila02() {
        if (numeroDeEntradas != 0) {            
            cargarCampos(lista.get(indiceEntradaActual));
            return lista.get(indiceEntradaActual).getFecha().getMonth() + 1;
        }
        return 0;
    }
    public int obtenerFilaEstablecida() {
        if (numeroDeEntradas != 0) {
            /*para buscar al quien esta establecido*/
            int bandera = 0;
            indiceEntradaActual = -1;
            for (MensualBE Me : lista) {
                indiceEntradaActual ++;
                if (Me.getEstableser()==1) {
                    cargarCampos(lista.get(indiceEntradaActual));
                    setEstableser(lista.get(indiceEntradaActual).getEstableser());
                    estableser();
                    bandera = 1;
                    return lista.get(indiceEntradaActual).getFecha().getMonth() + 1;
                }
            }
            if (bandera == 0) {
                indiceEntradaActual = 0;
                cargarCampos(lista.get(indiceEntradaActual));
                setEstableser(lista.get(indiceEntradaActual).getEstableser());
                return lista.get(indiceEntradaActual).getFecha().getMonth() + 1;
            }
        }
        return 0;
    }

    public void cargarCampos(MensualBE mensualBE) {
        this.mensualBE = mensualBE;
        lblId_Mes.setText("" + mensualBE.getId_Mensual());
        jdcFecha.setDate(mensualBE.getFecha());
//        JOptionPane.showMessageDialog(rootPane, mensualBE.getFecha());
        txtSaldoAnteriorR.setText("" + mensualBE.getSaldoanteriorr());
        txtEntradaR.setText("" + mensualBE.getEntradar());
        txtSalidaR.setText("" + mensualBE.getSalidar());
        txtSaldoRestanteR.setText("" + mensualBE.getSaldorestanter());

        txtSaldoAnteriorCC.setText("" + mensualBE.getSaldoanteriorcc());
        txtEntradaCC.setText("" + mensualBE.getEntradacc());
        txtSalidaCC.setText("" + mensualBE.getSalidacc());
        txtSaldoRestanteCC.setText("" + mensualBE.getSaldorestantecc());

        txtSaldoAnteriorO.setText("" + mensualBE.getSaldoanterioro());
        txtEntradaO.setText("" + mensualBE.getEntradao());
        txtSalidaO.setText("" + mensualBE.getSalidao());
        txtSaldoRestanteO.setText("" + mensualBE.getSaldorestanteo());

        txtTotFondMes.setText("" + mensualBE.getTotfondmes());
    }

    public void cargarCamposNuevo(MensualBE mensualBE) {
        this.mensualBE = mensualBE;
        lblId_Mes.setText("0");
        txtSaldoAnteriorR.setText("" + mensualBE.getSaldorestanter());
//        txtEntradaR.setText(""+mensualBE.getEntradar());
//        txtSalidaR.setText(""+mensualBE.getSalidar());
//        txtSaldoRestanteR.setText(""+mensualBE.getSaldorestanter());

        txtSaldoAnteriorCC.setText("" + mensualBE.getSaldorestantecc());
//        txtEntradaCC.setText(""+mensualBE.getEntradacc());
//        txtSalidaCC.setText(""+mensualBE.getSalidacc());
//        txtSaldoRestanteCC.setText(""+mensualBE.getSaldorestantecc());

        txtSaldoAnteriorO.setText("" + mensualBE.getSaldorestanteo());
//        txtEntradaO.setText(""+mensualBE.getEntradao());
//        txtSalidaO.setText(""+mensualBE.getSalidao());
//        txtSaldoRestanteO.setText(""+mensualBE.getSaldorestanteo());

//        txtTotFondMes.setText(""+mensualBE.getTotfondmes());
    }
    public void sumaTotal(){
        float a=0;
        float b = Float.parseFloat(txtSaldoRestanteR.getText());
        float c = Float.parseFloat(txtSaldoRestanteCC.getText());
        float d = Float.parseFloat(txtSaldoRestanteO.getText());
        a = b + c + d;
        txtTotFondMes.setText(""+a);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmMensual().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmMensual.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane EGRESO;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEstablecer;
    private javax.swing.JButton btnFiniquitar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPosterior;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JPanel jpCrud;
    private javax.swing.JPanel jpEgreso;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JSpinner jsnAnio;
    private javax.swing.JTable jtActual;
    private javax.swing.JTable jtLargoPlazo;
    private javax.swing.JLabel lblId_Mes;
    private javax.swing.JLabel lblMes;
    private javax.swing.JTextField txtEntradaCC;
    private javax.swing.JTextField txtEntradaO;
    private javax.swing.JTextField txtEntradaR;
    private javax.swing.JTextField txtEntradaR1;
    private javax.swing.JTextField txtSaldoAnteriorCC;
    private javax.swing.JTextField txtSaldoAnteriorO;
    private javax.swing.JTextField txtSaldoAnteriorR;
    private javax.swing.JTextField txtSaldoAnteriorR1;
    private javax.swing.JTextField txtSaldoRestanteCC;
    private javax.swing.JTextField txtSaldoRestanteO;
    private javax.swing.JTextField txtSaldoRestanteR;
    private javax.swing.JTextField txtSaldoRestanteR1;
    private javax.swing.JTextField txtSalidaCC;
    private javax.swing.JTextField txtSalidaO;
    private javax.swing.JTextField txtSalidaR;
    private javax.swing.JTextField txtSalidaR1;
    private javax.swing.JTextField txtTotFondMes;
    private javax.swing.JTextField txtTotalActuales;
    private javax.swing.JTextField txtTotalLargoPlazo;
    // End of variables declaration//GEN-END:variables

    public int getEstableser() {
        return estableser;
    }

    public void setEstableser(int estableser) {
        this.estableser = estableser;
    }
}
