/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HojaDeCuentaBD;

import HojaDeCuentaBE.ParametroBE;
import ejecutar.Coneccion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Loyola
 */
public class p_Parametro_ins {
    private int Accion;
    private int Id_Parametro ;
    private String Codigo ;
    private String Descripcion ;
    private int Id_Parametro_Origen;
    private int     Tipo;
    private String  FlagActivo ;
    private int ReturnVal;

    public p_Parametro_ins(Coneccion strCn,ParametroBE objParametroBE) throws SQLException {
        this.Accion = objParametroBE.getAccion();
        this.Id_Parametro = objParametroBE.getId_Parametro();
        this.Codigo = objParametroBE.getCodigo();
        this.Descripcion = objParametroBE.getDescripcion();
        this.Id_Parametro_Origen = objParametroBE.getId_Parametro_Origen();
        this.Tipo = objParametroBE.getTipo();
        this.FlagActivo = objParametroBE.getFlagActivo();
        this.ReturnVal = objParametroBE.getReturnVal();
        Connection con = strCn.getCon();
        Statement st=null;
        ResultSet rs=null; 
        try {            
            con.setAutoCommit(false);
            st = con.createStatement();
            //        this.ReturVal = ReturVal;
            if (this.Accion == 1){
                
                rs=st.executeQuery("SELECT max(ID_PARAMETRO) FROM Parametro");
                int idValidAnterior=0;
                while (rs.next()) {
                    idValidAnterior=rs.getInt(1);                    
                }
//              st.executeUpdate("CREATE TABLE USUARIO(Id_Usuario INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,Nombre VARCHAR(100),Password VARCHAR(100))");
                
                st.executeUpdate("INSERT INTO Parametro  (Codigo,Descripcion,Id_Parametro_Origen,Tipo,FlagActivo)VALUES("+
                    "'"+this.Codigo+"'"+
                    ",'"+this.Descripcion+"'"+
                    ","+this.Id_Parametro_Origen +
                    ","+this.Tipo +
                    ",'"+this.FlagActivo +
                        "')");
                rs=st.executeQuery("SELECT max(ID_PARAMETRO) FROM Parametro");
                int idActual=0;
                while (rs.next()) {
                    idActual=rs.getInt(1);                    
                }
                this.ReturnVal=-1;
                if (idValidAnterior<idActual) {
                    this.ReturnVal=idActual;
                }
//                st.close();               
            }
            if (this.Accion == 2){//CREACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("CREATE TABLE Parametro(" +
                                "    Id_Parametro int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" +
                                "    ,Codigo varchar(50) " +
                                "    ,Descripcion varchar(100) " +
                                "    ,Id_Parametro_Origen int " +
                                " )");
//              st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 3){//ELIMINACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("DROP TABLE Parametro");
//              st.close(); 
              this.ReturnVal=0;
            }
            con.commit();
            con.setAutoCommit(true);
            st.close();
        } catch (Exception e) {
            con.rollback();
            con.setAutoCommit(true);
            st.close();
            System.out.println(e);
            this.ReturnVal=-1;
        }        
    }
    public p_Parametro_ins(Connection strCn,ParametroBE objParametroBE) {
        this.Accion = objParametroBE.getAccion();
        this.Id_Parametro = objParametroBE.getId_Parametro();
        this.Codigo = objParametroBE.getCodigo();
        this.Descripcion = objParametroBE.getDescripcion();
        this.Id_Parametro_Origen = objParametroBE.getId_Parametro_Origen();
        this.ReturnVal = objParametroBE.getReturnVal();
    }

    public int getReturnVal() {
        return ReturnVal;
    }

    public void setReturnVal(int ReturnVal) {
        this.ReturnVal = ReturnVal;
    }
    
}
