package HojaDeCuentaBD;

import HojaDeCuentaBE.ParametroBE;
import ejecutar.Coneccion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class p_Parametro_upd {
    private int Accion;
    private int Id_Parametro ;
    private String Codigo;
    private String Descripcion;
    private int Id_Parametro_Origen;
    private String  FlagActivo;
    private int ReturnVal;
    public p_Parametro_upd(Coneccion strCn,ParametroBE objParametroBE) throws SQLException {
        this.Accion = objParametroBE.getAccion();
        this.Id_Parametro = objParametroBE.getId_Parametro();
        this.Codigo = objParametroBE.getCodigo();
        this.Descripcion = objParametroBE.getDescripcion();
        this.Id_Parametro_Origen = objParametroBE.getId_Parametro_Origen();
        this.FlagActivo = objParametroBE.getFlagActivo();
        this.ReturnVal = objParametroBE.getReturnVal();
        Connection con = strCn.getCon();
        Statement st=null;
        ResultSet rs=null;
        try {
            con.setAutoCommit(false);
            st = con.createStatement();
            //******************************************************************
            rs = st.executeQuery("SELECT*FROM PARAMETRO WHERE (CODIGO LIKE 'K_E%' OR CODIGO LIKE 'K_D%') AND ID_PARAMETRO = "+this.Id_Parametro);
            while (rs.next()) {
                throw new UnsupportedOperationException("Error al editar reegistros K_E,K_D");                 
            }            
            //******************************************************************
            if (this.Accion == 1){
                st.executeUpdate("UPDATE PARAMETRO SET "
                        +"CODIGO='"+this.Codigo+"'"
                        +",DESCRIPCION='"+this.Descripcion+"'"
                        +",Id_Parametro_Origen= "+this.Id_Parametro_Origen
               + " WHERE ID_PARAMETRO = "+this.Id_Parametro);
//                st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 2){//CREACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("CREATE TABLE Parametro(" +
                                "    Id_Parametro int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" +
                                "    ,Codigo varchar(50) " +
                                "    ,Descripcion varchar(100) " +
                                "    ,Id_Parametro_Origen int " +
                                " )");
//              st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 3){//ELIMINACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("DROP TABLE Parametro");
//              st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 4){//FLAGACTIVO = 0
              st.executeUpdate("UPDATE PARAMETRO SET FLAGACTIVO = '0' WHERE Id_Parametro = "+this.Id_Parametro);
              this.ReturnVal=0;
            }
            con.commit();
            con.setAutoCommit(true);
            st.close();
        } catch (Exception e) {
            con.rollback();
            con.setAutoCommit(true);
            st.close();
            System.out.println(e);
            this.ReturnVal=-1;
        }        
    }
    public p_Parametro_upd(Connection strCn,ParametroBE objParametroBE) {
        this.Accion = objParametroBE.getAccion();
        this.Id_Parametro = objParametroBE.getId_Parametro();
        this.Codigo = objParametroBE.getCodigo();
        this.Descripcion = objParametroBE.getDescripcion();
        this.Id_Parametro_Origen = objParametroBE.getId_Parametro_Origen();
        this.ReturnVal = objParametroBE.getReturnVal();
    }

    public int getReturnVal() {
        return ReturnVal;
    }

    public void setReturnVal(int ReturnVal) {
        this.ReturnVal = ReturnVal;
    }
    
}
